# Generated by Django 4.1.7 on 2023-05-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
